-- alter table if exists cart
--     drop constraint if exists FKioh3c0mo0al2kswtnk5r09y7f;
  
-- alter table if exists cart_items
--     drop constraint if exists FK99e0am9jpriwxcm6is7xfedy3;
  
-- alter table if exists cart_items
--     drop constraint if exists FK1re40cjegsfvw58xrkdp6bac6;
 
-- alter table if exists delivery_settings
--     drop constraint if exists FK6orqe7rs5h8vuauophnpy31oc;
 
-- alter table if exists inventory
--     drop constraint if exists FKq2yge7ebtfuvwufr6lwfwqy9l;
  
-- alter table if exists inventory
--     drop constraint if exists FKh74vmk9mabyg8mjj0xlccup3v;
 
-- alter table if exists order_items
--     drop constraint if exists FKbioxgbv59vetrxe0ejfubep1w;
 
-- alter table if exists order_items
--     drop constraint if exists FKocimc7dtr037rh4ls4l95nlfi;
 
-- alter table if exists orders
--     drop constraint if exists FKpxtb8awmi0dk6smoh2vp1litg;
 
-- alter table if exists orders
--     drop constraint if exists FK2kigpmp1rdwf2164yy6bx09dd;
 
-- alter table if exists products
--     drop constraint if exists FKog2rp4qthbtt2lfyhfo32lsw9;
 
-- alter table if exists products
--     drop constraint if exists FKs6kdu75k7ub4s95ydsr52p59s;
  
-- alter table if exists vendor_access_accounts
--     drop constraint if exists FKhvdmpjbwb8qex2v7lxx646d55;
 
-- alter table if exists vendor_shops
--     drop constraint if exists FKff105dn0w9wpfpmc905l3y92o;
 
-- alter table if exists vendors
--     drop constraint if exists FKmvrnkjpgn0jcn1xs8g4cucjv3;
 
-- drop table if exists cart cascade;

-- drop table if exists cart_items cascade;

-- drop table if exists categories cascade;

-- drop table if exists customers cascade;

-- drop table if exists delivery_settings cascade;

-- drop table if exists inventory cascade;  

-- drop table if exists order_items cascade;

-- drop table if exists orders cascade;

-- drop table if exists products cascade;

-- drop table if exists vendor_access_accounts cascade;
  
-- drop table if exists vendor_shops cascade;
 
-- drop table if exists vendors cascade;

-- create table cart (
--     created_at timestamp(6),
--     customer_id bigint not null unique,
--     id bigint generated by default as identity,
--     updated_at timestamp(6),
--     primary key (id)
-- );

-- create table cart_items (
--     quantity integer not null,
--     cart_id bigint not null,
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     product_id bigint not null,
--     updated_at timestamp(6),
--     primary key (id)
-- );

  
-- create table categories (
--     is_active boolean not null,
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     updated_at timestamp(6),
--     description varchar(500),
--     image_url varchar(255),
--     name varchar(255) not null unique,
--     primary key (id)
-- );
 
-- create table customers (
--     dob date not null,
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     updated_at timestamp(6),
--     email varchar(255) not null unique,
--     name varchar(255) not null,
--     password varchar(255) not null,
--     phone_number varchar(255) not null unique,
--     primary key (id)
-- );
  
-- create table delivery_settings (
--     base_fee numeric(38,2) not null,
--     rate_per_km numeric(38,2) not null,
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     updated_at timestamp(6),
--     vendor_shop_id bigint not null unique,
--     primary key (id)
-- );
  
-- create table inventory (
--     quantity integer not null,
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     product_id bigint not null,
--     updated_at timestamp(6),
--     vendor_shop_id bigint not null,
--     primary key (id)
-- );
 
-- create table order_items (
--     quantity integer not null,
--     unit_price numeric(38,2) not null,
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     order_id bigint not null,
--     product_id bigint not null,
--     special_instructions varchar(255),
--     primary key (id)
-- );
  
-- create table orders (
--     delivery_fee numeric(38,2),
--     sub_total_amount numeric(38,2) not null,
--     created_at timestamp(6),
--     customer_id bigint not null,
--     id bigint generated by default as identity,
--     updated_at timestamp(6),
--     vendor_shop_id bigint not null,
--     delivery_address varchar(255),
--     order_number varchar(255) not null unique,
--     payment_method varchar(255) check (payment_method in ('CASH','CREDIT_CARD')),
--     payment_status varchar(255) not null check (payment_status in ('PENDING','PAID','FAILED','REFUNDED')),
--     status varchar(255) not null check (status in ('PENDING','CONFIRMED','PREPARING','READY_FOR_PICKUP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')),
--     primary key (id)
-- );
  
-- create table products (
--     is_available boolean not null,
--     is_deleted boolean not null,
--     price numeric(38,2) not null,
--     category_id bigint not null,
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     updated_at timestamp(6),
--     vendor_id bigint not null,
--     description varchar(1000),
--     image_url varchar(255),
--     name varchar(255) not null,
--     primary key (id)
-- );
  
-- create table vendor_access_accounts (
--     failed_login_attempts integer not null,
--     is_active boolean not null,
--     account_locked_until timestamp(6),
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     last_login timestamp(6),
--     updated_at timestamp(6),
--     vendor_id bigint not null,
--     email varchar(255) not null unique,
--     password varchar(255) not null,
--     primary key (id)
-- );
  
-- create table vendor_shops (
--     closing_time time(6),
--     is_active boolean not null,
--     is_delivery_available boolean not null,
--     last_order_time time(6),
--     opening_time time(6),
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     updated_at timestamp(6),
--     vendor_id bigint not null,
--     address varchar(255) not null,
--     email varchar(255),
--     logo_url varchar(255),
--     name varchar(255) not null,
--     phone_number varchar(255) not null,
--     primary key (id)
-- );
  
-- create table vendors (
--     is_active boolean not null,
--     created_at timestamp(6),
--     id bigint generated by default as identity,
--     updated_at timestamp(6),
--     vendor_access_account_id bigint not null unique,
--     email varchar(255) not null unique,
--     image_url varchar(255),
--     name varchar(255) not null,
--     phone_number varchar(255) not null,
--     primary key (id)
-- );


-- create index idx_customers_phone_number on customers (phone_number);

-- create index idx_shop_quantity_product on inventory (vendor_shop_id, quantity, product_id);

-- create index idx_order_id on order_items (order_id);

-- create index idx_orders_customer_status on orders (customer_id, status);

-- create index idx_orders_vendor_status on orders (vendor_shop_id, status);

-- create index idx_created_at on orders (created_at);

-- create index idx_vendor_name_price_category on products (vendor_id, name, price, category_id);

-- create index idx_vendor_available on products (vendor_id, is_available, is_deleted);

-- create index idx_vendor_id on vendor_shops (vendor_id);

-- create index idx_vendor_id_name_address on vendor_shops (vendor_id, name, address, phone_number);

-- create index idx_vendor_is_active_name on vendors (is_active, name);

-- alter table if exists cart
--     add constraint FKioh3c0mo0al2kswtnk5r09y7f
--     foreign key (customer_id)
--     references customers;

-- alter table if exists cart_items
--     add constraint FK99e0am9jpriwxcm6is7xfedy3
--     foreign key (cart_id)
--     references cart;

-- alter table if exists cart_items
--     add constraint FK1re40cjegsfvw58xrkdp6bac6
--     foreign key (product_id)
--     references products;

-- alter table if exists delivery_settings
--     add constraint FK6orqe7rs5h8vuauophnpy31oc
--     foreign key (vendor_shop_id)
--     references vendor_shops;

-- alter table if exists inventory
--     add constraint FKq2yge7ebtfuvwufr6lwfwqy9l
--     foreign key (product_id)
--     references products;

-- alter table if exists inventory
--     add constraint FKh74vmk9mabyg8mjj0xlccup3v
--     foreign key (vendor_shop_id)
--     references vendor_shops;

-- alter table if exists order_items
--     add constraint FKbioxgbv59vetrxe0ejfubep1w
--     foreign key (order_id)
--     references orders;

-- alter table if exists order_items
--     add constraint FKocimc7dtr037rh4ls4l95nlfi
--     foreign key (product_id)
--     references products;

-- alter table if exists orders
--     add constraint FKpxtb8awmi0dk6smoh2vp1litg
--     foreign key (customer_id)
--     references customers;

-- alter table if exists orders
--     add constraint FK2kigpmp1rdwf2164yy6bx09dd
--     foreign key (vendor_shop_id)
--     references vendor_shops;

-- alter table if exists products
--     add constraint FKog2rp4qthbtt2lfyhfo32lsw9
--     foreign key (category_id)
--     references categories;

-- alter table if exists products
--     add constraint FKs6kdu75k7ub4s95ydsr52p59s
--     foreign key (vendor_id)
--     references vendors;

-- alter table if exists vendor_access_accounts
--     add constraint FKhvdmpjbwb8qex2v7lxx646d55
--     foreign key (vendor_id)
--     references vendors;

-- alter table if exists vendor_shops
--     add constraint FKff105dn0w9wpfpmc905l3y92o
--     foreign key (vendor_id)
--     references vendors;

-- alter table if exists vendors
--     add constraint FKmvrnkjpgn0jcn1xs8g4cucjv3
--     foreign key (vendor_access_account_id)
--     references vendor_access_accounts;