
    create table addition_groups (
        max_selectable integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        vendor_id bigint not null,
        name varchar(255) not null,
        primary key (id),
        constraint idx_vendor_group_name unique (vendor_id, name)
    );

    create table additions (
        price numeric(10,2) not null,
        created_at timestamp(6),
        group_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        name varchar(255) not null,
        primary key (id)
    );

    create table admin (
        id bigint generated by default as identity,
        email varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table cart (
        created_at timestamp(6),
        customer_id bigint not null unique,
        id bigint generated by default as identity,
        shop_id bigint,
        updated_at timestamp(6),
        primary key (id)
    );

    create table cart_items (
        quantity integer not null,
        cart_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        option_id bigint,
        updated_at timestamp(6),
        additions_ids Text,
        primary key (id)
    );

    create table categories (
        is_active boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        image_url varchar(255),
        name varchar(255) not null,
        primary key (id),
        unique (name)
    );

    create table customers (
        dob date not null,
        is_email_verified boolean,
        is_phone_verified boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        password varchar(255) not null,
        phone_number varchar(255) not null unique,
        saved_address varchar(255),
        primary key (id)
    );

    create table delivery_areas (
        price numeric(38,2),
        id bigint generated by default as identity,
        vendor_shop_id bigint not null,
        area varchar(255),
        city varchar(255),
        governorate varchar(255),
        primary key (id)
    );

    create table delivery_settings (
        base_fee float(53) not null,
        is_delivery_available boolean,
        rate_per_km float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        vendor_shop_id bigint not null unique,
        delivery_approach varchar(255) check (delivery_approach in ('DISTANCE','AREA')),
        primary key (id)
    );

    create table idempotent_requests (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        version bigint,
        idempotency_key varchar(255) not null,
        request_hash varchar(255) not null,
        status varchar(255) not null check (status in ('PENDING','COMPLETED','FAILED')),
        response_json oid,
        primary key (id),
        unique (idempotency_key, user_id)
    );

    create table inventory (
        quantity integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6),
        vendor_shop_id bigint not null,
        primary key (id),
        constraint uk_inventory_shop_product unique (vendor_shop_id, product_id)
    );

    create table order_item_additions (
        price numeric(10,2) not null,
        addition_id bigint,
        id bigint generated by default as identity,
        order_item_id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table order_items (
        quantity integer not null,
        unit_price numeric(38,2) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        option_id bigint not null,
        order_id bigint not null,
        primary key (id)
    );

    create table orders (
        delivery_fee numeric(38,2),
        latitude float(53),
        longitude float(53),
        sub_total_amount numeric(38,2) not null,
        created_at timestamp(6),
        customer_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        vendor_shop_id bigint not null,
        delivery_address varchar(255),
        order_number varchar(255) not null unique,
        order_type varchar(255) not null check (order_type in ('PICKUP','DELIVERY','IN_HOUSE')),
        payment_method varchar(255) check (payment_method in ('CASH','CREDIT_CARD','INSTAPAY')),
        payment_status varchar(255) not null check (payment_status in ('PENDING','PAID','FAILED','REFUNDED')),
        pickup_time varchar(255),
        status varchar(255) not null check (status in ('PENDING','PREPARING','READY_FOR_PICKUP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')),
        primary key (id)
    );

    create table product_addition_groups (
        addition_group_id bigint not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        primary key (id),
        constraint uk_product_group unique (product_id, addition_group_id)
    );

    create table product_options (
        price numeric(38,2) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        size varchar(255) check (size in ('DEFAULT','SMALL','MEDIUM','LARGE')),
        primary key (id)
    );

    create table products (
        is_deleted boolean not null,
        is_stock_tracked boolean,
        category_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        vendor_id bigint not null,
        description varchar(1000),
        image_url varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table reset_password_tokens (
        customer_id bigint not null unique,
        expiry_date timestamp(6) not null,
        id bigint generated by default as identity,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table shop_additions (
        is_available boolean not null,
        addition_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        shop_id bigint not null,
        updated_at timestamp(6),
        primary key (id),
        constraint uk_shop_addition unique (shop_id, addition_id)
    );

    create table shop_product (
        is_available boolean,
        id bigint generated by default as identity,
        product_id bigint,
        vendor_shop_id bigint,
        primary key (id),
        unique (vendor_shop_id, product_id)
    );

    create table vendor_access_accounts (
        failed_login_attempts integer not null,
        is_active boolean not null,
        account_locked_until timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        last_login timestamp(6),
        updated_at timestamp(6),
        vendor_id bigint not null unique,
        email varchar(255) not null unique,
        password varchar(255) not null,
        primary key (id)
    );

    create table vendor_blocked_customers (
        customer_id bigint not null,
        vendor_shop_id bigint not null,
        primary key (customer_id, vendor_shop_id)
    );

    create table vendor_shops (
        is_active boolean not null,
        is_online boolean not null,
        is_online_payment_available boolean not null,
        latitude float(53),
        longitude float(53),
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        vendor_id bigint not null,
        address varchar(255) not null,
        city varchar(255) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        phone_number varchar(255) not null,
        primary key (id)
    );

    create table vendors (
        is_active boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        image_url varchar(255),
        name varchar(255) not null,
        phone_number varchar(255) not null,
        primary key (id)
    );

    create table verification_tokens (
        customer_id bigint not null unique,
        expiry_date timestamp(6) not null,
        id bigint generated by default as identity,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table verified_customers (
        is_verified boolean,
        customer_id bigint not null,
        id bigint generated by default as identity,
        last_updated_by_shop_id bigint not null,
        vendor_id bigint not null,
        verified_at timestamp(6) not null,
        primary key (id),
        unique (customer_id, vendor_id)
    );

    create index idx_customer_phone_number
       on customers (phone_number, first_name);

    create index idx_customer_email
       on customers (email);

    create index IDXqt6hgwig0e1ps058vy9iq2597
       on delivery_settings (vendor_shop_id, base_fee, rate_per_km);

    create index idx_shop_quantity
       on inventory (vendor_shop_id, quantity);

    create index idx_shop_product_quantity
       on inventory (vendor_shop_id, product_id, quantity);

    create index idx_order_id
       on order_items (order_id);

    create index idx_order_customer_id
       on orders (customer_id, status, order_number, payment_status);

    create index idx_order_vendor_shop_id
       on orders (vendor_shop_id, payment_status, status);

    create index idx_order_created_at
       on orders (created_at);

    create index idx_order_number
       on orders (order_number);

    create index idx_product_id
       on product_options (id, product_id);

    create index idx_vendor_category
       on products (vendor_id, category_id);

    create index idx_vendor_stock_tracked
       on products (vendor_id, is_stock_tracked);

    create index idx_vendor_id
       on vendor_shops (vendor_id);

    create index idx_vendor_email
       on vendor_shops (email);

    create index idx_vendor_id_name_address
       on vendor_shops (vendor_id, name, address, phone_number);

    create index idx_latitude_longitude_city
       on vendor_shops (latitude, longitude, city);

    create index idx_vendor_is_active_name
       on vendors (is_active, name);

    create index idx_customer_vendor
       on verified_customers (customer_id, vendor_id);

    alter table if exists addition_groups
       add constraint FKsp8pq4a3klqw530g14kveyd5m
       foreign key (vendor_id)
       references vendors;

    alter table if exists additions
       add constraint FKj9hxahw3rnq1nn8u0yetfhx0e
       foreign key (group_id)
       references addition_groups;

    alter table if exists cart
       add constraint FKioh3c0mo0al2kswtnk5r09y7f
       foreign key (customer_id)
       references customers;

    alter table if exists cart
       add constraint FKktclvbsw41rubfvus7ucrpkjh
       foreign key (shop_id)
       references vendor_shops;

    alter table if exists cart_items
       add constraint FK99e0am9jpriwxcm6is7xfedy3
       foreign key (cart_id)
       references cart;

    alter table if exists cart_items
       add constraint FK4vx0eo9n788fd4qrmhkjcyrhn
       foreign key (option_id)
       references product_options;

    alter table if exists delivery_areas
       add constraint FKqoin0u9mghiqmfcisompke3e6
       foreign key (vendor_shop_id)
       references vendor_shops;

    alter table if exists delivery_settings
       add constraint FK6orqe7rs5h8vuauophnpy31oc
       foreign key (vendor_shop_id)
       references vendor_shops;

    alter table if exists inventory
       add constraint FKq2yge7ebtfuvwufr6lwfwqy9l
       foreign key (product_id)
       references products;

    alter table if exists inventory
       add constraint FKh74vmk9mabyg8mjj0xlccup3v
       foreign key (vendor_shop_id)
       references vendor_shops;

    alter table if exists order_item_additions
       add constraint FKcc2onx8qmrjdg7a4kk39id2ku
       foreign key (order_item_id)
       references order_items;

    alter table if exists order_items
       add constraint FKbioxgbv59vetrxe0ejfubep1w
       foreign key (order_id)
       references orders;

    alter table if exists order_items
       add constraint FKpjfxxp4p3oux0k0eu636w9xgi
       foreign key (option_id)
       references product_options;

    alter table if exists orders
       add constraint FKpxtb8awmi0dk6smoh2vp1litg
       foreign key (customer_id)
       references customers;

    alter table if exists orders
       add constraint FK2kigpmp1rdwf2164yy6bx09dd
       foreign key (vendor_shop_id)
       references vendor_shops;

    alter table if exists product_addition_groups
       add constraint FK1j4qokx2d8sha57201csqny72
       foreign key (addition_group_id)
       references addition_groups;

    alter table if exists product_addition_groups
       add constraint FKrs6klqb89ca8yabwwkphw52eq
       foreign key (product_id)
       references products;

    alter table if exists product_options
       add constraint FK8vv4f8fru80wxocwgxwsrow61
       foreign key (product_id)
       references products;

    alter table if exists products
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9
       foreign key (category_id)
       references categories;

    alter table if exists products
       add constraint FKs6kdu75k7ub4s95ydsr52p59s
       foreign key (vendor_id)
       references vendors;

    alter table if exists reset_password_tokens
       add constraint FKa37nadd0p675xw8kds9ciko6l
       foreign key (customer_id)
       references customers;

    alter table if exists shop_additions
       add constraint FKtrmibmbf6olq0p14xxp5en2ub
       foreign key (addition_id)
       references additions;

    alter table if exists shop_additions
       add constraint FKe6onftsxkc1mv1ltsop3ir1q2
       foreign key (shop_id)
       references vendor_shops;

    alter table if exists shop_product
       add constraint FKubxhxe1ahvu51e4lcm752mh0
       foreign key (product_id)
       references products;

    alter table if exists shop_product
       add constraint FK8oh8d7a0y55dda46deysymx67
       foreign key (vendor_shop_id)
       references vendor_shops;

    alter table if exists vendor_access_accounts
       add constraint FKhvdmpjbwb8qex2v7lxx646d55
       foreign key (vendor_id)
       references vendors;

    alter table if exists vendor_blocked_customers
       add constraint FKgrseyf56lli49w9auv439sbs2
       foreign key (customer_id)
       references customers;

    alter table if exists vendor_blocked_customers
       add constraint FK725ewkm2bfsruqfp7k3bgidwx
       foreign key (vendor_shop_id)
       references vendor_shops;

    alter table if exists vendor_shops
       add constraint FKff105dn0w9wpfpmc905l3y92o
       foreign key (vendor_id)
       references vendors;

    alter table if exists verification_tokens
       add constraint FK7pe7epeuy8eg14s0shhwnbts6
       foreign key (customer_id)
       references customers;

    alter table if exists verified_customers
       add constraint FKphjafmv5rboeieuebn1s3wur2
       foreign key (customer_id)
       references customers;

    alter table if exists verified_customers
       add constraint FK4el5gsk2r5awfcm6gq66rtxju
       foreign key (last_updated_by_shop_id)
       references vendor_shops;

    alter table if exists verified_customers
       add constraint FK7noqcib3yeytpxl229ij6bdo0
       foreign key (vendor_id)
       references vendors;
