---- 1. Add 'status' column
---- We default existing rows to 'PENDING' to satisfy the @Column(nullable = false) constraint.
--ALTER TABLE idempotent_requests
--ADD COLUMN status VARCHAR(50) DEFAULT 'PENDING' NOT NULL;
--
---- (Optional) Remove the default constraint if you want the app to explicitly provide status in the future
--ALTER TABLE idempotent_requests
--ALTER COLUMN status DROP DEFAULT;
--
---- 2. Add 'response_json' column
---- Using TEXT is preferred over OID/CLOB for JSON content in PostgreSQL
--ALTER TABLE idempotent_requests
--ADD COLUMN response_json TEXT;
--
---- 3. Add 'updated_at' column
--ALTER TABLE idempotent_requests
--ADD COLUMN updated_at TIMESTAMP;
--
---- (Data Migration) Fill 'updated_at' with 'created_at' for existing rows so it isn't null
--UPDATE idempotent_requests
--SET updated_at = created_at
--WHERE updated_at IS NULL;
--
---- 4. Add 'version' column for Optimistic Locking
---- We default to 0 for existing rows
--ALTER TABLE idempotent_requests
--ADD COLUMN version BIGINT DEFAULT 0 NOT NULL;
--
--ALTER TABLE idempotent_requests ALTER COLUMN user_id SET NOT NULL;
--ALTER TABLE idempotent_requests ALTER COLUMN idempotency_key SET NOT NULL;
--ALTER TABLE idempotent_requests ALTER COLUMN request_hash SET NOT NULL;